import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },
    {
      type: 'doc',
      id: 'live-demo',
      label: '▶ Live Demo',
    },
    {
      type: 'doc',
      id: 'installation',
      label: 'Installation & Configuration',
    },
    {
      type: 'category',
      label: 'Authentication',
      link: { type: 'doc', id: 'authentication/authentication' },
      items: [
        'authentication/local',
        'authentication/oauth',
        'authentication/magic-link',
        'authentication/totp',
        'authentication/sms',
      ],
    },
    {
      type: 'category',
      label: 'Database',
      link: { type: 'doc', id: 'database/database' },
      items: [
        'database/in-memory',
        'database/sqlite',
        'database/mysql',
        'database/mongodb',
        'database/postgresql',
        'database/postgrest',
        'database/php-crud-api',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api-reference/api-reference' },
      items: [
        'api-reference/endpoints',
        'api-reference/template-store',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      link: { type: 'doc', id: 'advanced/advanced' },
      items: [
        'advanced/built-in-ui',
        'advanced/browser-client',
        'advanced/idp-mode',
        'advanced/sessions',
        'advanced/roles-permissions',
        'advanced/multi-tenancy',
        'advanced/cors',
        'advanced/csrf',
        'advanced/user-metadata',
        'advanced/extending-interfaces',
        'advanced/account-linking',
        'advanced/admin',
        'advanced/bearer-token',
        'advanced/mailer',
        'advanced/email-verification',
        'advanced/change-email',
        'advanced/account-deletion',
        'advanced/custom-claims',
        'advanced/auth-event-bus',
        'advanced/api-keys',
        'advanced/auth-tools',
        'advanced/sse',
        'advanced/sse-scaling',
        'advanced/sse-notify-decorator',
        'advanced/webhooks',
        'advanced/telemetry',
        'advanced/swagger',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      link: { type: 'doc', id: 'frameworks/frameworks' },
      items: [
        'frameworks/express',
        'frameworks/nestjs',
        'frameworks/nextjs',
        'frameworks/framework-agnostic',
        'frameworks/angular',
        'frameworks/ng-awesome-node-auth',
        'frameworks/react',
        'frameworks/python',
        'frameworks/dart',
        'frameworks/go',
        'frameworks/lambda',
        'frameworks/rust',
        'frameworks/flutter',
        'frameworks/ios',
        'frameworks/android',
      ],
    },
  ],
};

export default sidebars;
